name: Pandore CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Installation des dépendances
        run: npm ci # "npm ci" est plus rapide et strict que "npm install" en CI

      - name: Vérification des types (TypeScript)
        run: npm run typecheck

      - name: Analyse statique (ESLint)
        run: npm run lint

      - name: Vérification du build Next.js
        run: npm run build

      - name: Build Docker image
        # Cette étape échouera si vous n'avez pas encore de fichier "Dockerfile"
        run: docker build -t pandore-app .
